import { AppThemeId, AppThemePalette } from "./types";

export const THEMES: Record<AppThemeId, AppThemePalette> = {
  studydeck: {
    id: "studydeck",
    name: "StudyDeck",
    description: "Academic Field Journal + Study RPG",
    light: {
      accent: "#654A3A",
      accentLight: "#EAE3D8",
      accentMuted: "#D6CCBF",
      accentText: "#332821",
      background: "#F2EEE6",
      surface: "#F7F3EA",
      surfaceMuted: "#EAE3D8",
      foreground: "#29231F",
      mutedText: "#756C64",
      border: "#D6CCBF",
      progressBar: "#D79A45",
      selection: "#E8DEC8",
    },
    dark: {
      accent: "#D79A45",
      accentLight: "#382A1E",
      accentMuted: "#49372D",
      accentText: "#F0C078",
      background: "#181411",
      surface: "#221B17",
      surfaceMuted: "#2E2520",
      foreground: "#F2EEE6",
      mutedText: "#9E9186",
      border: "#3D322B",
      progressBar: "#D79A45",
      selection: "#382A1E",
    },
  },

  midnight: {
    id: "midnight",
    name: "Midnight",
    description: "Deep navy with cool blue accents",
    light: {
      accent: "#1B2A4A",
      accentLight: "#E0E7FF",
      accentMuted: "#A5B4FC",
      accentText: "#1B2A4A",
      background: "#F0F2F8",
      surface: "#FFFFFF",
      surfaceMuted: "#EEF0F8",
      foreground: "#0F172A",
      mutedText: "#64748B",
      border: "#E2E8F0",
      progressBar: "#1B2A4A",
      selection: "#E0E7FF",
    },
    dark: {
      accent: "#818CF8",
      accentLight: "#1E1B3A",
      accentMuted: "#3730A3",
      accentText: "#A5B4FC",
      background: "#07090F",
      surface: "#0F1219",
      surfaceMuted: "#161C2A",
      foreground: "#E2E8F0",
      mutedText: "#94A3B8",
      border: "#1E2A3A",
      progressBar: "#6366F1",
      selection: "#1E1B3A",
    },
  },

  forest: {
    id: "forest",
    name: "Forest",
    description: "Muted sage greens, grounded and calm",
    light: {
      accent: "#166534",
      accentLight: "#DCFCE7",
      accentMuted: "#86EFAC",
      accentText: "#166534",
      background: "#F7F9F7",
      surface: "#FFFFFF",
      surfaceMuted: "#F0F4F0",
      foreground: "#14291F",
      mutedText: "#4B7A5A",
      border: "#D1E8D5",
      progressBar: "#16A34A",
      selection: "#DCFCE7",
    },
    dark: {
      accent: "#4ADE80",
      accentLight: "#052E16",
      accentMuted: "#166534",
      accentText: "#86EFAC",
      background: "#080E0A",
      surface: "#0E1A11",
      surfaceMuted: "#162119",
      foreground: "#ECFDF5",
      mutedText: "#6EE7B7",
      border: "#1A2E1E",
      progressBar: "#22C55E",
      selection: "#052E16",
    },
  },

  sakura: {
    id: "sakura",
    name: "Sakura",
    description: "Soft blush tones, elegant and warm",
    light: {
      accent: "#9D174D",
      accentLight: "#FCE7F3",
      accentMuted: "#F9A8D4",
      accentText: "#9D174D",
      background: "#FDF7F9",
      surface: "#FFFFFF",
      surfaceMuted: "#FDF2F8",
      foreground: "#1F1217",
      mutedText: "#9D4E68",
      border: "#F3C5D5",
      progressBar: "#DB2777",
      selection: "#FCE7F3",
    },
    dark: {
      accent: "#F472B6",
      accentLight: "#4A0E2C",
      accentMuted: "#9D174D",
      accentText: "#FBCFE8",
      background: "#0F080B",
      surface: "#1A0F13",
      surfaceMuted: "#241319",
      foreground: "#FDF2F8",
      mutedText: "#F9A8D4",
      border: "#3A1622",
      progressBar: "#EC4899",
      selection: "#4A0E2C",
    },
  },

  ocean: {
    id: "ocean",
    name: "Ocean",
    description: "Muted teal-blue, refreshing and focused",
    light: {
      accent: "#0E7490",
      accentLight: "#CFFAFE",
      accentMuted: "#67E8F9",
      accentText: "#0E7490",
      background: "#F5FAFB",
      surface: "#FFFFFF",
      surfaceMuted: "#ECFAFA",
      foreground: "#0C1E24",
      mutedText: "#2E7A8A",
      border: "#B3E5EC",
      progressBar: "#0891B2",
      selection: "#CFFAFE",
    },
    dark: {
      accent: "#22D3EE",
      accentLight: "#0A2432",
      accentMuted: "#0E7490",
      accentText: "#A5F3FC",
      background: "#050C10",
      surface: "#0A1520",
      surfaceMuted: "#0F1F2C",
      foreground: "#ECFEFF",
      mutedText: "#67E8F9",
      border: "#0E2938",
      progressBar: "#06B6D4",
      selection: "#0A2432",
    },
  },

  lavender: {
    id: "lavender",
    name: "Lavender",
    description: "Soft violet, dreamy and creative",
    light: {
      accent: "#6D28D9",
      accentLight: "#EDE9FE",
      accentMuted: "#C4B5FD",
      accentText: "#5B21B6",
      background: "#F8F7FF",
      surface: "#FFFFFF",
      surfaceMuted: "#F3F0FF",
      foreground: "#1A1030",
      mutedText: "#7C5CA8",
      border: "#DDD6FE",
      progressBar: "#7C3AED",
      selection: "#EDE9FE",
    },
    dark: {
      accent: "#A78BFA",
      accentLight: "#2D1B69",
      accentMuted: "#5B21B6",
      accentText: "#C4B5FD",
      background: "#0A070F",
      surface: "#130D20",
      surfaceMuted: "#1C142E",
      foreground: "#F5F3FF",
      mutedText: "#C4B5FD",
      border: "#2D1B69",
      progressBar: "#8B5CF6",
      selection: "#2D1B69",
    },
  },

  latte: {
    id: "latte",
    name: "Latte",
    description: "Warm beige and brown, cozy and grounded",
    light: {
      accent: "#78350F",
      accentLight: "#FEF3C7",
      accentMuted: "#FCD34D",
      accentText: "#78350F",
      background: "#FDFAF6",
      surface: "#FFFBF5",
      surfaceMuted: "#FEF3E2",
      foreground: "#1C1007",
      mutedText: "#92400E",
      border: "#E8D5B7",
      progressBar: "#D97706",
      selection: "#FEF3C7",
    },
    dark: {
      accent: "#FBBF24",
      accentLight: "#3D1F00",
      accentMuted: "#92400E",
      accentText: "#FDE68A",
      background: "#100A02",
      surface: "#1C1208",
      surfaceMuted: "#261A0E",
      foreground: "#FFFBF0",
      mutedText: "#FCD34D",
      border: "#3D2A10",
      progressBar: "#F59E0B",
      selection: "#3D1F00",
    },
  },

  mono: {
    id: "mono",
    name: "Mono",
    description: "Clean neutral grayscale, distraction-free",
    light: {
      accent: "#1F2937",
      accentLight: "#F3F4F6",
      accentMuted: "#9CA3AF",
      accentText: "#111827",
      background: "#F9FAFB",
      surface: "#FFFFFF",
      surfaceMuted: "#F3F4F6",
      foreground: "#111827",
      mutedText: "#6B7280",
      border: "#E5E7EB",
      progressBar: "#374151",
      selection: "#E5E7EB",
    },
    dark: {
      accent: "#D1D5DB",
      accentLight: "#1F2937",
      accentMuted: "#374151",
      accentText: "#F9FAFB",
      background: "#080A0C",
      surface: "#111318",
      surfaceMuted: "#1A1D22",
      foreground: "#F9FAFB",
      mutedText: "#9CA3AF",
      border: "#1F2937",
      progressBar: "#6B7280",
      selection: "#1F2937",
    },
  },
};

export const THEME_ORDER: AppThemeId[] = [
  "studydeck",
  "midnight",
  "forest",
  "sakura",
  "ocean",
  "lavender",
  "latte",
  "mono",
];
